services:
  db:
    image: postgres:alpine
    container_name: db-dev
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - '5432:5432'
    networks:
      - network-bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USER"]
      interval: 5s
      retries: 5
      timeout: 5s

networks:
  network-bridge:
    driver: bridge
