services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - '5432:5432'
    networks:
      - network-bridge

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://$DATABASE_USER:$DATABASE_PASSWORD@db:5432/$DATABASE_NAME
    networks:
      - network-bridge
    depends_on:
      - db
    command: ['pnpm', 'start']

networks:
  network-bridge:
    driver: bridge
